name: 'autodocs-engine'
description: 'Analyze TypeScript codebase and comment on PRs with AI context insights'
branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  anthropic-api-key:
    description: 'Anthropic API key for architecture + domain synthesis (optional — structural analysis works without it)'
    required: false
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Run autodocs-engine analysis
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
      run: npx autodocs-engine@latest analyze . --dry-run --quiet > /tmp/autodocs-analysis.json || true

    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');

          let analysis;
          try {
            analysis = JSON.parse(fs.readFileSync('/tmp/autodocs-analysis.json', 'utf8'));
          } catch {
            core.info('No analysis output found — skipping PR comment');
            return;
          }

          const packages = analysis.packages ?? [];
          if (packages.length === 0) {
            core.info('No packages in analysis — skipping PR comment');
            return;
          }

          const pkg = packages[0];

          // Build comment body
          let body = `## AGENTS.md Analysis\n\n`;

          // Multi-package summary
          if (packages.length > 1) {
            body += `**${packages.length} packages analyzed:**\n`;
            for (const p of packages) {
              body += `- **${p.name}** — ${p.files.total} files, ${p.publicAPI.length} exports\n`;
            }
            body += `\n`;
          }

          body += `**${pkg.name}** — ${pkg.role?.summary || pkg.architecture?.packageType || 'TypeScript package'}\n\n`;

          // Metrics table
          body += `| Metric | Value |\n|--------|-------|\n`;
          body += `| Files analyzed | ${pkg.files.total} |\n`;
          body += `| Public API exports | ${pkg.publicAPI.length} |\n`;
          body += `| Conventions detected | ${pkg.conventions.length} |\n`;
          body += `| Package manager | ${pkg.commands.packageManager} |\n`;
          if (pkg.isMetaTool) {
            body += `| Meta-tool | Yes (${pkg.metaToolInfo.supportedFamilies.length} framework ecosystems) |\n`;
          }
          body += `\n`;

          // Commands
          const cmds = pkg.commands;
          if (cmds.build || cmds.test || cmds.lint) {
            body += `### Commands\n\n`;
            body += `| Command | Type |\n|---------|------|\n`;
            if (cmds.build) body += `| \`${cmds.build.run}\` | Build |\n`;
            if (cmds.test) body += `| \`${cmds.test.run}\` | Test |\n`;
            if (cmds.lint) body += `| \`${cmds.lint.run}\` | Lint |\n`;
            if (cmds.start) body += `| \`${cmds.start.run}\` | Start |\n`;
            body += `\n`;
          }

          // Top conventions
          const topConvs = pkg.conventions.slice(0, 5);
          if (topConvs.length > 0) {
            body += `### Key Conventions\n\n`;
            for (const c of topConvs) {
              body += `- ${c.name}\n`;
            }
            body += `\n`;
          }

          // Workflow rules
          const rules = analysis.crossPackage?.workflowRules || [];
          if (rules.length > 0) {
            body += `### Workflow Rules\n\n`;
            for (const r of rules) {
              body += `- **${r.trigger}** — ${r.action}\n`;
            }
            body += `\n`;
          }

          // Meta-tool supported frameworks
          if (pkg.isMetaTool && pkg.metaToolInfo?.supportedFamilies?.length > 0) {
            body += `### Supported Frameworks\n\n`;
            body += `${pkg.metaToolInfo.supportedFamilies.join(', ')}\n\n`;
          }

          body += `---\n`;
          body += `*Generated by [autodocs-engine](https://github.com/msiric/autodocs-engine) in ${(analysis.meta.timingMs / 1000).toFixed(1)}s*\n`;
          body += `*Run \`npx autodocs-engine init\` to generate a full AGENTS.md for your project*`;

          // Find existing comment to update (avoids duplicate comments on push)
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          const marker = '## AGENTS.md Analysis';
          const existing = comments.find(c => c.body?.includes(marker));

          if (existing) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existing.id,
              body,
            });
            core.info('Updated existing PR comment');
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
            core.info('Created PR comment');
          }
