// @ts-nocheck
/* eslint-disable */
// This file is automatically generated. Do not edit.

export interface GetDataQuery {
  data: {
    id: string;
    name: string;
  };
}

export interface GetDataQueryVariables {
  id: string;
}
