// @ts-nocheck
/* eslint-disable */
// This file is automatically generated. Do not edit.

export interface UpdateDataMutation {
  updateData: {
    id: string;
    success: boolean;
  };
}

export interface UpdateDataMutationVariables {
  id: string;
  name: string;
}
